language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake


